name: DSHMobile
options:
  bundleIdPrefix: com.hoya.dsh
  deploymentTarget:
    iOS: '17.5'
  xcodeVersion: '15.4'
packages:
  DSHMobileProtocol:
    path: ProtocolKit
  IrohLib:
    url: https://github.com/n0-computer/iroh-ffi.git
    revision: 5e451092dba0c1a09ee83ff6e5be37b1152a5c58
targets:
  DSHMobile:
    type: application
    platform: iOS
    sources:
      - App
    dependencies:
      - package: DSHMobileProtocol
      - package: IrohLib
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hoya.dsh.mobile
        TARGETED_DEVICE_FAMILY: '1'
        SWIFT_VERSION: '5.0'
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Manual
    info:
      path: App/Info.plist
      properties:
        CFBundleDisplayName: DSH Mobile
        CFBundleShortVersionString: 1.0.3
        CFBundleVersion: '4'
        LSRequiresIPhoneOS: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UILaunchScreen:
          UIColorName: LaunchBackground
schemes:
  DSHMobile:
    build:
      targets:
        DSHMobile: all
